select * from customer limit 20

--Q1 what is the total revenue generated by male vs female customer ?

select gender , sum(purchase_amount) from customer group by gender

--Q2 Which customer used a discount but still spent more then the average purchase amount ?

SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer)


--Q3 Which are the top 5 product the with highest  average review rating ?

select item_purchased, ROUND(avg(review_rating::numeric),2) as average_rating  from customer  group by item_purchased  order by  average_rating desc limit 5;

--Q4 Compare the  average purchase amount  between standard and express shipping.

select shipping_type ,
ROUND(avg(purchase_amount),2)
from customer 
where shipping_type in ('Standard','Express')
GROUP BY shipping_type

--Q5 DO Subscribe  customer spend more ? compare average spend and total revenue b/w 
--subscriber  and non subscriber .

select subscription_status,
count(customer_id) as total_customer,
ROUND(avg(purchase_amount),2) as avge_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue ,avge_spend desc;

--Q6 Which 5 product  have the highest  percentage  of purchases with discount applied
 select item_purchased ,
 ROUND(100 * SUM(CASE WHEN  discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS Discount_rate
 from customer 
 group by item_purchased  
 order by discount_rate desc
 limit 5;

-- Q7,segment  customers into the , returning  , and loyal  based on their  total 
-- number  of previos , and show the count of each segment 


with customer_type as (
select  customer_id , previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from customer 
)
select customer_segment ,count(*)as " Number of customer"
from customer_type
group by customer_segment


--Q8 WHAT are the top 3 most purchased products within each  category ?
with item_count as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER()OVER(Partition by category order by count (customer_id)desc)as item_rank
from customer 
group by category , item_purchased
)

select item_rank ,category , item_purchased , total_orders
from item_count
where item_rank <=3

-- Q9 ARE Customer who are repeat buyer (more than 5 previous purchase )also lilely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases >5
group by subscription_status



